
package web_services_soap.marketplace;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MarketPlaceImplementationService", targetNamespace = "http://marketplace.web_services_soap/", wsdlLocation = "http://localhost:9999/ws/marketplace?wsdl")
public class MarketPlaceImplementationService
    extends Service
{

    private final static URL MARKETPLACEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MARKETPLACEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName MARKETPLACEIMPLEMENTATIONSERVICE_QNAME = new QName("http://marketplace.web_services_soap/", "MarketPlaceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/marketplace?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKETPLACEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        MARKETPLACEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public MarketPlaceImplementationService() {
        super(__getWsdlLocation(), MARKETPLACEIMPLEMENTATIONSERVICE_QNAME);
    }

    public MarketPlaceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKETPLACEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public MarketPlaceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, MARKETPLACEIMPLEMENTATIONSERVICE_QNAME);
    }

    public MarketPlaceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKETPLACEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public MarketPlaceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketPlaceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MarketPlaceInterface
     */
    @WebEndpoint(name = "MarketPlaceImplementationPort")
    public MarketPlaceInterface getMarketPlaceImplementationPort() {
        return super.getPort(new QName("http://marketplace.web_services_soap/", "MarketPlaceImplementationPort"), MarketPlaceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketPlaceInterface
     */
    @WebEndpoint(name = "MarketPlaceImplementationPort")
    public MarketPlaceInterface getMarketPlaceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://marketplace.web_services_soap/", "MarketPlaceImplementationPort"), MarketPlaceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKETPLACEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw MARKETPLACEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return MARKETPLACEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
